// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcRqArOcVOV1yGzhFyB40JHkd62o9TisU',
    appId: '1:960448262830:web:3ed95b8161df59afc5f33f',
    messagingSenderId: '960448262830',
    projectId: 'axlerate-customer-portal',
    authDomain: 'axlerate-customer-portal.firebaseapp.com',
    storageBucket: 'axlerate-customer-portal.appspot.com',
    measurementId: 'G-DX2QLY0GEB',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: "AIzaSyAr4JxUrT-gQBq_gWtWFczfXInzXTlM2fI",
    authDomain: "axlerate-portal-dev.firebaseapp.com",
    projectId: "axlerate-portal-dev",
    storageBucket: "axlerate-portal-dev.appspot.com",
    messagingSenderId: "722126722783",
    appId: "1:722126722783:web:0437197fbd3a1ec254fb6a",
    measurementId: "G-YJN65CMZVF",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeAQ_iTYbUIgdcPxpvHPaVvn5E2iiXV8U',
    appId: '1:960448262830:android:e22d45f0b71b87b5c5f33f',
    messagingSenderId: '960448262830',
    projectId: 'axlerate-customer-portal',
    storageBucket: 'axlerate-customer-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOOZLvUzPMekjliNLjJAMgfFUXJwbBqg0',
    appId: '1:960448262830:ios:5fb5f7facbf3840cc5f33f',
    messagingSenderId: '960448262830',
    projectId: 'axlerate-customer-portal',
    storageBucket: 'axlerate-customer-portal.appspot.com',
    iosClientId: '960448262830-m0vd8hgedfoeegbirkciqttik7houk5i.apps.googleusercontent.com',
    iosBundleId: 'com.axlerate.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOOZLvUzPMekjliNLjJAMgfFUXJwbBqg0',
    appId: '1:960448262830:ios:5fb5f7facbf3840cc5f33f',
    messagingSenderId: '960448262830',
    projectId: 'axlerate-customer-portal',
    storageBucket: 'axlerate-customer-portal.appspot.com',
    iosClientId: '960448262830-m0vd8hgedfoeegbirkciqttik7houk5i.apps.googleusercontent.com',
    iosBundleId: 'com.axlerate.portal',
  );
}
